name: async-timer
version: '0.2.0.0'
synopsis: Provides API for timer based execution of IO actions
description: ! 'This is a lightweight package built on top of the async package

  providing easy to use periodic timers. This can be used for executing

  IO actions periodically.'
category: Concurrency
author: Moritz Clasmeier
maintainer: mtesseract@silverratio.net
copyright: (c) 2016-2018 Moritz Clasmeier
license: BSD3
github: mtesseract/async-timer
extra-source-files:
- README.md
library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -fno-warn-type-defaults
  exposed-modules:
  - Control.Concurrent.Async.Timer
  dependencies:
  - base >= 4.9.1.0 && < 5
  - safe-exceptions >= 0.1.5.0 && < 0.2
  - transformers-base >= 0.4.4 && < 0.5
  - unliftio >= 0.2.4.0 && < 0.3
  - unliftio-core >= 0.1.1.0 && < 0.2
  - safe-exceptions >= 0.1.7.0 && < 0.2
  - async >= 2.2.1 && < 2.3
tests:
  async-timer-test:
    main: Spec.hs
    source-dirs: test
    default-extensions:
    - OverloadedStrings
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - async-timer
    - HUnit
    - test-framework
    - test-framework-hunit
    - containers
    - criterion
